[build]
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "echo 'No build command'"
  port = 8888

[[redirects]]
  from = "/api/send-sms"
  to = "/.netlify/functions/send-sms"
  status = 200

[[redirects]]
  from = "/api/submit-review"
  to = "/.netlify/functions/submit-review"
  status = 200

[[redirects]]
  from = "/api/get-reviews"
  to = "/.netlify/functions/get-reviews"
  status = 200

[[redirects]]
  from = "/api/embed"
  to = "/.netlify/functions/embed"
  status = 200

[[redirects]]
  from = "/api/update-featured"
  to = "/.netlify/functions/update-featured"
  status = 200

[[redirects]]
  from = "/api/create-business"
  to = "/.netlify/functions/create-business"
  status = 200

[[redirects]]
  from = "/api/admin-send-invite"
  to = "/.netlify/functions/admin-send-invite"
  status = 200

[[redirects]]
  from = "/api/admin-get-businesses"
  to = "/.netlify/functions/admin-get-businesses"
  status = 200

[[redirects]]
  from = "/api/admin-update-business"
  to = "/.netlify/functions/admin-update-business"
  status = 200

[[redirects]]
  from = "/api/update-business"
  to = "/.netlify/functions/update-business"
  status = 200
